apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: P8E80F9AEF21F6940
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: P8E80F9AEF21F6940
          matcherRegex: 'correlationId: ([a-f0-9-]{36})'
          name: CorrelationID
          url: '{env="local"} |= "$${__value.raw}"'
          urlDisplayLabel: Ver todos los logs de esta petición
        - datasourceUid: P8E80F9AEF21F6940
          matcherRegex: 'Transaction ([a-f0-9-]{36})'
          name: TransactionID
          url: '{service="transaction-service"} |= "$${__value.raw}"'
          urlDisplayLabel: Ver logs de esta transacción
